version: "3"

services:
  frontend:
    container_name: todo_frontend
    build: ./frontend
    command: npm run start
    ports:
      - "8800:3000"
    volumes:
      - ./frontend/:/usr/src/app/

  backend:
    container_name: todo_backend
    build: ./backend
    command: npm run start
    ports:
      - "8801:3000"

  db:
    container_name: todo_db
    image: mongo:latest
    logging:
      driver: "none"
    volumes:
      - todo_volume:/data/db
#
#  auth:
#    container_name: auth_app
#    build: ./auth
#    command: npm run start
#    restart: unless-stopped
#    depends_on:
#      - auth_db
#    ports:
#      - "3002:3002"
#    environment:
#      PORT: 3002
#      DB: "mongodb://auth_db:27017/test"
#      API_URL: "http://api:3001/api"
#
#  auth_db:
#    container_name: auth_db
#    image: mongo:latest
#    logging:
#      driver: "none"
#    volumes:
#      - todo_volume:/data/db
#
#  nginx:
#    container_name: nginx_proxy
#    image: nginx:stable-alpine
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
#    depends_on:
#      - frontend

volumes:
  todo_volume:
